# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, allowed to be list of directories separated by semicolon
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value is passed to dateutil.tz.gettz()
# timezone = UTC

# max length of characters to associate with the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# version_path_separator = :

# set to 'true' to write the output to a file or standard output as UTF-8
# output_encoding = utf-8

# The URL will be overridden dynamically in env.py from the environment variable DATABASE_URL
sqlalchemy.url = postgresql+asyncpg://neeron_user:pwd@localhost:5432/neeron

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
