"""initial_migration

Revision ID: 8f8107ac11cc
Revises: None
Create Date: 2026-06-24 18:00:18.963852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8107ac11cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # Ensure extensions exist (if PostgreSQL)
    if op.get_bind().dialect.name == "postgresql":
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
        op.execute('CREATE EXTENSION IF NOT EXISTS timescaledb')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',

    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable farm name (e.g. 'Loch Awe — Scotland')."),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False, comment='WGS-84 decimal latitude (−90 … +90).'),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False, comment='WGS-84 decimal longitude (−180 … +180).'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment="IANA timezone string (e.g. 'Europe/Oslo')."),
    sa.Column('carrying_capacity_kg', sa.Numeric(precision=12, scale=2), nullable=False, comment='Maximum licensed biomass capacity in kilograms.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('carrying_capacity_kg > 0', name='ck_farm_capacity_positive'),
    sa.CheckConstraint('latitude  BETWEEN -90  AND  90', name='ck_farm_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_farm_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=True)
    op.create_table('historical_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Short, human-readable case title shown in the UI.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed narrative describing the incident conditions.'),
    sa.Column('scenario_type', sa.String(length=100), nullable=False, comment="Machine-readable category used by the similarity engine. e.g. 'Dissolved Oxygen Depletion' | 'Sea Lice Influx' | 'High Ammonia Event' | 'Thermal Stress' | 'Gill Disease'."),
    sa.Column('severity', sa.String(length=50), nullable=False, comment="Impact severity: 'Low' | 'Medium' | 'High' | 'Critical'."),
    sa.Column('outcome', sa.Text(), nullable=False, comment='Factual description of what occurred (observable result).'),
    sa.Column('resolution', sa.Text(), nullable=False, comment='Step-by-step corrective actions taken. Surfaced by the recommendation engine as proven remediation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('Low','Medium','High','Critical')", name='ck_historical_case_severity_valid'),
    sa.PrimaryKeyConstraint('id'),
    comment='CBR case catalog — curated historical incidents and resolutions. Feeds the recommendation engine via case_matches.'
    )
    op.create_index('ix_historical_cases_scenario_type', 'historical_cases', ['scenario_type'], unique=False)
    op.create_index('ix_historical_cases_severity', 'historical_cases', ['severity'], unique=False)
    op.create_table('pathogens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=False, comment="Full scientific / taxonomic name (e.g. 'Lepeophtheirus salmonis')."),
    sa.Column('common_name', sa.String(length=100), nullable=False, comment="Common name used in the UI (e.g. 'Sea Lice')."),
    sa.Column('risk_threshold_count', sa.Numeric(precision=6, scale=2), nullable=False, comment='Detection count above which a Warning alert is triggered.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name'),
    comment='Reference catalog of monitored aquaculture pathogens.'
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Human-readable role label (e.g. 'Administrator')."),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='JSON map of permission keys to boolean grants.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_health_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID identifier for the system health snapshot.'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Snapshot recording timestamp (TimescaleDB partition key).'),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Global system health score [0.00 - 100.00].'),
    sa.Column('latency_ms', sa.Numeric(precision=8, scale=2), nullable=False, comment='Average API response latency in milliseconds.'),
    sa.Column('uptime_pct', sa.Numeric(precision=5, scale=2), nullable=False, comment='Global system uptime percentage [0.00 - 100.00].'),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=4), nullable=False, comment='Proportion of failed API and ingestion requests [0.0 - 1.0].'),
    sa.Column('active_users', sa.Integer(), nullable=False, comment='Count of active users concurrently on the platform.'),
    sa.Column('active_models', sa.Integer(), nullable=False, comment='Count of registered AI/ML models currently operational in production.'),
    sa.Column('active_alerts_count', sa.Integer(), nullable=False, comment='Count of currently active/unresolved alerts across all farms.'),
    sa.CheckConstraint('error_rate BETWEEN 0 AND 1', name='ck_system_health_snapshot_error_rate_range'),
    sa.CheckConstraint('health_score BETWEEN 0 AND 100', name='ck_system_health_snapshot_score_range'),
    sa.CheckConstraint('uptime_pct BETWEEN 0 AND 100', name='ck_system_health_snapshot_uptime_range'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    comment='TimescaleDB hypertable — periodic snapshots of global system/infrastructure health. Partition: recorded_at / 30-day chunks.'
    )
    op.create_index('ix_system_health_snapshots_recorded', 'system_health_snapshots', ['recorded_at'], unique=False)
    op.create_table('case_matches',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the CBR engine produced this match (TimescaleDB partition key).'),
    sa.Column('prediction_id', sa.Uuid(), nullable=False, comment='UUID of the source prediction. Use prediction_type to determine which hypertable to join. Stored without a DB-level FK to support cross-hypertable polymorphism.'),
    sa.Column('prediction_type', sa.String(), nullable=False, comment="Discriminator: 'psi' | 'disease' | 'mortality' | 'harvest'."),
    sa.Column('case_id', sa.Uuid(), nullable=False, comment='FK → historical_cases.id'),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Cosine / embedding similarity between prediction features and case [0.0 … 1.0].'),
    sa.CheckConstraint("prediction_type IN ('psi','disease','mortality','harvest')", name='ck_case_match_prediction_type_valid'),
    sa.CheckConstraint('similarity_score BETWEEN 0 AND 1', name='ck_case_match_similarity_range'),
    sa.ForeignKeyConstraint(['case_id'], ['historical_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'matched_at'),
    comment='TimescaleDB hypertable — CBR engine: prediction-to-case similarity matches. Partition: matched_at / 30-day chunks.'
    )
    op.create_index('ix_case_matches_case_id', 'case_matches', ['case_id'], unique=False)
    op.create_index('ix_case_matches_prediction', 'case_matches', ['prediction_id', 'matched_at'], unique=False)
    op.create_index('ix_case_matches_similarity', 'case_matches', ['prediction_id', 'similarity_score'], unique=False)
    op.create_table('farm_health_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID identifier for the snapshot.'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Snapshot recording timestamp (TimescaleDB partition key).'),
    sa.Column('farm_id', sa.Uuid(), nullable=False, comment='FK → farms.id'),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Overall calculated health score for the farm [0.00 - 100.00].'),
    sa.Column('psi_average', sa.Numeric(precision=5, scale=4), nullable=False, comment='Weighted average of all tank PSI predictions on the farm [0.0 - 1.0].'),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Calculated biosecurity/disease risk score for the farm [0.0 - 1.0].'),
    sa.Column('active_alerts', sa.Integer(), nullable=False, comment='Count of active alerts for the farm at recording time.'),
    sa.Column('active_recommendations', sa.Integer(), nullable=False, comment='Count of active recommendation actions pending for the farm.'),
    sa.CheckConstraint('health_score BETWEEN 0 AND 100', name='ck_farm_health_snapshot_score_range'),
    sa.CheckConstraint('psi_average BETWEEN 0 AND 1', name='ck_farm_health_snapshot_psi_range'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 1', name='ck_farm_health_snapshot_risk_range'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    comment='TimescaleDB hypertable — periodic snapshots of farm aggregate health metrics. Partition: recorded_at / 30-day chunks.'
    )
    op.create_index('ix_farm_health_snapshots_farm_recorded', 'farm_health_snapshots', ['farm_id', 'recorded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False, comment='FK → roles.id  (CASCADE restriction keeps orphan‑safety).'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique login email address.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt / Argon2 hashed password.'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable without deleting the record.'),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=128), nullable=True, comment='Base-32 TOTP secret (stored encrypted at rest).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False, comment='FK → farms.id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Zone label, unique within the parent farm.'),
    sa.Column('description', sa.Text(), nullable=True, comment="Free-text description of the zone's purpose or layout."),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'name', name='uq_zone_farm_name')
    )
    op.create_index(op.f('ix_zones_farm_id'), 'zones', ['farm_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Unique model name (e.g. 'PSI Predictor v2', 'Sea Lice Classifier')."),
    sa.Column('algorithm', sa.String(length=100), nullable=False, comment="ML algorithm family: 'LSTM' | 'XGBoost' | 'Random Forest' | 'Transformer' | 'CNN' | 'Ensemble' | 'Rule-Based' | 'Other'."),
    sa.Column('description', sa.Text(), nullable=False, comment="Narrative description of the model's purpose, inputs, and outputs."),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Development' | 'Staging' | 'Production' | 'Deprecated'."),
    sa.Column('owner_id', sa.Uuid(), nullable=True, comment='FK → users.id — data scientist or team lead responsible for this model.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('Development','Staging','Production','Deprecated')", name='ck_ai_model_status_valid'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='AI/ML model registry — one row per named model. Versioning via model_versions. Anchors the MLOps traceability chain.'
    )
    op.create_index('ix_ai_models_algorithm', 'ai_models', ['algorithm'], unique=False)
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=True)
    op.create_index(op.f('ix_ai_models_owner_id'), 'ai_models', ['owner_id'], unique=False)
    op.create_index('ix_ai_models_status', 'ai_models', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Event timestamp (TimescaleDB partition key).'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Categorised event (e.g. 'THRESHOLD_UPDATED')."),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='FK → users.id  (nullable for system events).'),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('time', 'event_type')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id  (1-to-1).'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('critical_alerts_only', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Notification delivery timestamp (TimescaleDB partition key).'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id  (notification recipient).'),
    sa.Column('alert_id', sa.Uuid(), nullable=False, comment='UUID of the source alert (alerts.id). Stored as plain UUID (not FK) because hypertable composite FKs require both partition columns — use app-layer join when needed.'),
    sa.Column('alert_time', sa.DateTime(timezone=True), nullable=False, comment='alerts.time of the source alert — retained for join queries.'),
    sa.Column('delivery_channel', sa.String(length=50), nullable=False, comment="Channel used: 'in_app' | 'email' | 'sms' | 'push'."),
    sa.Column('priority', sa.String(length=50), nullable=False, comment="Mirrors source alert severity: 'Info' | 'Warning' | 'Critical'."),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='True once the user has viewed this notification in the UI.'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the notification was marked as read.'),
    sa.CheckConstraint("delivery_channel IN ('in_app','email','sms','push')", name='ck_notification_channel_valid'),
    sa.CheckConstraint("priority IN ('Info','Warning','Critical')", name='ck_notification_priority_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — per-user notification inbox. Partition: time / 30-day chunks.'
    )
    op.create_index('ix_notifications_read_status', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_notifications_user_time', 'notifications', ['user_id', 'time'], unique=False)
    op.create_table('tanks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False, comment='FK → zones.id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable tank label (e.g. 'TNK-01'). Unique per zone."),
    sa.Column('type', sa.String(length=50), nullable=False, comment="Structural type: 'RAS Tank' | 'Sea Cage' | 'Nursery'."),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=2), nullable=False, comment='Tank volume in cubic metres.'),
    sa.Column('max_biomass_kg', sa.Numeric(precision=12, scale=2), nullable=False, comment='Maximum safe stocking biomass in kilograms.'),
    sa.Column('species', sa.String(length=100), nullable=False, comment="Primary species stocked (default: 'Atlantic Salmon')."),
    sa.Column('digital_twin_config', sa.JSON(), nullable=False, comment='Optional Digital Twin model parameters (JSON).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('RAS Tank', 'Sea Cage', 'Nursery')", name='ck_tank_type_valid'),
    sa.CheckConstraint('max_biomass_kg > 0', name='ck_tank_biomass_positive'),
    sa.CheckConstraint('volume_m3 > 0', name='ck_tank_volume_positive'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'name', name='uq_tank_zone_name')
    )
    op.create_index(op.f('ix_tanks_zone_id'), 'tanks', ['zone_id'], unique=False)
    op.create_table('threshold_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False, comment='FK → farms.id — threshold applies to all tanks within this farm.'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment="Water quality parameter: 'temperature' | 'pH' | 'dissolved_oxygen' | 'ammonia' | 'salinity'."),
    sa.Column('warning_min', sa.Numeric(precision=10, scale=4), nullable=False, comment="Lower warning threshold. Values below this trigger a 'Warning' severity alert."),
    sa.Column('warning_max', sa.Numeric(precision=10, scale=4), nullable=False, comment="Upper warning threshold. Values above this trigger a 'Warning' severity alert."),
    sa.Column('critical_min', sa.Numeric(precision=10, scale=4), nullable=False, comment="Lower critical threshold. Values below this trigger a 'Critical' severity alert."),
    sa.Column('critical_max', sa.Numeric(precision=10, scale=4), nullable=False, comment="Upper critical threshold. Values above this trigger a 'Critical' severity alert."),
    sa.Column('updated_by', sa.Uuid(), nullable=True, comment='FK → users.id — last operator who modified this threshold config.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Auto-updated timestamp — shown in Settings page audit column.'),
    sa.CheckConstraint("metric_name IN ('temperature','pH','dissolved_oxygen','ammonia','salinity')", name='ck_threshold_metric_name_valid'),
    sa.CheckConstraint('critical_min <= warning_min', name='ck_threshold_critical_min_lte_warning_min'),
    sa.CheckConstraint('warning_max <= critical_max', name='ck_threshold_warning_max_lte_critical_max'),
    sa.CheckConstraint('warning_min <= warning_max', name='ck_threshold_warning_min_lte_warning_max'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'metric_name', name='uq_threshold_farm_metric'),
    comment='Per-farm water quality threshold bands. Powers the Settings & Operations Control page. Alert engine reads these to classify sensor readings.'
    )
    op.create_index('ix_threshold_configs_farm', 'threshold_configs', ['farm_id'], unique=False)
    op.create_index('ix_threshold_configs_metric', 'threshold_configs', ['metric_name'], unique=False)
    op.create_index(op.f('ix_threshold_configs_updated_by'), 'threshold_configs', ['updated_by'], unique=False)
    op.create_table('user_farm_mappings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'farm_id')
    )
    op.create_table('compliance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False, comment='FK → farms.id  (compliance is typically at farm level).'),
    sa.Column('tank_id', sa.Uuid(), nullable=True, comment='FK → tanks.id  (optional: if compliance event is tank-specific).'),
    sa.Column('compliance_type', sa.String(length=100), nullable=False, comment='Category of compliance event.'),
    sa.Column('authority', sa.String(length=150), nullable=False, comment="Regulatory authority or body (e.g. 'Marine Scotland', 'Mattilsynet')."),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Official reference or case number from the regulatory body.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Compliant' | 'Pending Review' | 'Non-Compliant' | 'Expired'."),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Deadline for submission or renewal.'),
    sa.Column('resolved_at', sa.Date(), nullable=True, comment='Date compliance was confirmed by the authority.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='Soft-archive flag to hide historical records from active views.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("compliance_type IN ('Regulatory Inspection','Chemical Usage Approval','Licence Renewal','Treatment Notification','Environmental Impact Report','Other')", name='ck_compliance_type_valid'),
    sa.CheckConstraint("status IN ('Compliant','Pending Review','Non-Compliant','Expired')", name='ck_compliance_status_valid'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Regulatory compliance records per farm — audit trail for inspections and certifications.'
    )
    op.create_index('ix_compliance_records_farm', 'compliance_records', ['farm_id'], unique=False)
    op.create_index('ix_compliance_records_type_status', 'compliance_records', ['compliance_type', 'status'], unique=False)
    op.create_table('digital_twin_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('simulation_time', sa.DateTime(timezone=True), nullable=False, comment='The simulated point in time (NOT wall-clock). TimescaleDB partition key.'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id — the tank being simulated.'),
    sa.Column('scenario_name', sa.String(length=100), nullable=False, comment="Simulation scenario label. e.g. 'Baseline' | 'Increased Feed +10%' | 'Reduced Stocking' | 'Aeration Boost'."),
    sa.Column('simulated_biomass', sa.Numeric(precision=12, scale=2), nullable=False, comment='Projected total live weight (kg) of the fish population at simulation_time.'),
    sa.Column('simulated_growth', sa.Numeric(precision=10, scale=4), nullable=False, comment='Projected daily growth rate in grams per fish per day (g/fish/day).'),
    sa.Column('simulated_oxygen', sa.Numeric(precision=10, scale=4), nullable=False, comment='Projected dissolved oxygen concentration (mg/L) at simulation_time.'),
    sa.CheckConstraint('simulated_biomass >= 0', name='ck_dt_biomass_non_negative'),
    sa.CheckConstraint('simulated_growth >= 0', name='ck_dt_growth_non_negative'),
    sa.CheckConstraint('simulated_oxygen >= 0', name='ck_dt_oxygen_non_negative'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'simulation_time'),
    comment='TimescaleDB hypertable — Digital Twin scenario simulation snapshots. Partition: simulation_time / 30-day chunks.'
    )
    op.create_index('ix_digital_twin_scenario', 'digital_twin_snapshots', ['scenario_name', 'simulation_time'], unique=False)
    op.create_index('ix_digital_twin_tank_sim_time', 'digital_twin_snapshots', ['tank_id', 'simulation_time'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('inspector_id', sa.Uuid(), nullable=False, comment='FK → users.id  (RESTRICT prevents losing the audit trail).'),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_tank_id'), 'inspections', ['tank_id'], unique=False)
    op.create_table('ml_feature_store',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('feature_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Observation timestamp of the underlying data — NOT the compute time. Ensures point-in-time correct retraining (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id — the tank this feature was computed for.'),
    sa.Column('feature_name', sa.String(length=150), nullable=False, comment="Machine-readable feature name (e.g. 'temp_rolling_mean_1h', 'do_lag_15m', 'psi_ma_7d')."),
    sa.Column('feature_group', sa.String(length=50), nullable=False, comment="'telemetry' | 'biological' | 'environmental' | 'engineered'."),
    sa.Column('source_table', sa.String(length=100), nullable=False, comment="Source table name from which this feature was derived. e.g. 'tank_environment_snapshots' | 'tank_production_metrics' | 'telemetry'."),
    sa.Column('feature_value', sa.Numeric(precision=18, scale=6), nullable=True, comment='Scalar feature value. NULL for vector/embedding features (use feature_vector).'),
    sa.Column('feature_vector', sa.JSON(), nullable=True, comment='JSON array or object for multi-dimensional features (e.g. embedding vectors, frequency-domain features).'),
    sa.CheckConstraint("feature_group IN ('telemetry','biological','environmental','engineered')", name='ck_ml_feature_group_valid'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'feature_timestamp'),
    comment='TimescaleDB hypertable — pre-computed ML features for inference and retraining. Partition: feature_timestamp / 7-day chunks.'
    )
    op.create_index('ix_ml_feature_store_group_ts', 'ml_feature_store', ['feature_group', 'feature_timestamp'], unique=False)
    op.create_index('ix_ml_feature_store_source', 'ml_feature_store', ['source_table', 'feature_timestamp'], unique=False)
    op.create_index('ix_ml_feature_store_tank_ts', 'ml_feature_store', ['tank_id', 'feature_timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False, comment='FK → ai_models.id'),
    sa.Column('version_tag', sa.String(length=50), nullable=False, comment="Semantic version string (e.g. 'v2.1.0'). Unique per model."),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True, comment="URI of the serialised model artefact. e.g. 's3://neeron-models/psi-predictor/v2.1.0/model.pkl' or 'mlflow://experiments/42/runs/abc123/artifacts/model'."),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional release notes or changelog for this version.'),
    sa.Column('hyperparameters', sa.JSON(), nullable=False, comment='Training hyperparameters (JSON) — stored for reproducibility.'),
    sa.Column('metrics', sa.JSON(), nullable=False, comment='Final evaluation metrics from training/validation (JSON).'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Active' | 'Testing' | 'Archived'."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True for the currently deployed (production) version. Only one version per model should be active at a time (enforced at application layer).'),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when training completed.'),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this version was promoted to production. NULL = not yet deployed.'),
    sa.CheckConstraint("status IN ('Active','Testing','Archived')", name='ck_model_version_status_valid'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version_tag', name='uq_model_version_tag'),
    comment='Model version registry — one row per trained artefact. Critical FK target for prediction tables and ai_insights to support full MLOps traceability.'
    )
    op.create_index('ix_model_versions_is_active', 'model_versions', ['model_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_index('ix_model_versions_model_status', 'model_versions', ['model_id', 'status'], unique=False)
    op.create_table('quarantine_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False, comment="Severity level: 'Low' | 'Medium' | 'High' | 'Critical'."),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the quarantine event began.'),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True, comment='When the quarantine was lifted; NULL if still active.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High', 'Critical')", name='ck_quarantine_severity_valid'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantine_events_tank_id'), 'quarantine_events', ['tank_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=True, comment='FK → tanks.id  (nullable: sensor may be unassigned / in storage).'),
    sa.Column('hardware_id', sa.String(length=100), nullable=False, comment='Globally unique hardware/MAC identifier burned into firmware.'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Measurement type this sensor produces.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Operational status of the device.'),
    sa.Column('calibration_due_at', sa.DateTime(timezone=True), nullable=True, comment='Next mandatory calibration deadline (NULL = not yet scheduled).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('Active','Warning','Calibration Overdue','Offline')", name='ck_sensor_status_valid'),
    sa.CheckConstraint("type IN ('temperature','pH','dissolved_oxygen','ammonia','salinity','feeder','aerator')", name='ck_sensor_type_valid'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='IoT sensor registry — one row per physical device.'
    )
    op.create_index(op.f('ix_sensors_hardware_id'), 'sensors', ['hardware_id'], unique=True)
    op.create_index(op.f('ix_sensors_tank_id'), 'sensors', ['tank_id'], unique=False)
    op.create_table('tank_environment_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable identifier for ML feature linkage.'),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False, comment='Snapshot bucket timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True, comment='Water temperature in °C (−5.00 … 40.00).'),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True, comment='pH value (0.00 … 14.00).'),
    sa.Column('dissolved_oxygen', sa.Numeric(precision=6, scale=2), nullable=True, comment='Dissolved oxygen concentration in mg/L (≥ 0).'),
    sa.Column('salinity', sa.Numeric(precision=6, scale=2), nullable=True, comment='Salinity in PSU / g/kg (≥ 0).'),
    sa.Column('ammonia', sa.Numeric(precision=6, scale=4), nullable=True, comment='Total ammonia nitrogen (TAN) in mg/L (≥ 0).'),
    sa.Column('turbidity', sa.Numeric(precision=6, scale=2), nullable=True, comment='Water turbidity in NTU (≥ 0).'),
    sa.CheckConstraint('ammonia >= 0', name='ck_env_snapshot_ammonia_non_negative'),
    sa.CheckConstraint('dissolved_oxygen >= 0', name='ck_env_snapshot_do_non_negative'),
    sa.CheckConstraint('ph BETWEEN 0.00 AND 14.00', name='ck_env_snapshot_ph_range'),
    sa.CheckConstraint('salinity >= 0', name='ck_env_snapshot_salinity_non_negative'),
    sa.CheckConstraint('temperature BETWEEN -5.00 AND 40.00', name='ck_env_snapshot_temp_range'),
    sa.CheckConstraint('turbidity >= 0', name='ck_env_snapshot_turbidity_non_negative'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'captured_at'),
    comment='TimescaleDB hypertable — pivoted per-tank environmental snapshots. Partition: captured_at / 7-day chunks.'
    )
    op.create_index('ix_env_snapshot_tank_captured', 'tank_environment_snapshots', ['tank_id', 'captured_at'], unique=False)
    op.create_table('tank_production_metrics',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable identifier for harvest prediction linkage.'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Observation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('population', sa.Integer(), nullable=False, comment='Live fish count in the tank at time of recording (≥ 0).'),
    sa.Column('biomass_kg', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total live weight (kg) — population × average_weight_g / 1000.'),
    sa.Column('average_weight_g', sa.Numeric(precision=10, scale=2), nullable=False, comment='Mean individual fish weight in grams (≥ 0).'),
    sa.Column('fcr', sa.Numeric(precision=4, scale=2), nullable=False, comment='Feed Conversion Ratio — kg feed consumed / kg biomass gained. Industry target: < 1.20 for Atlantic Salmon.'),
    sa.Column('feed_consumption_kg', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total feed delivered to tank during this period (kg).'),
    sa.Column('mortality_rate', sa.Numeric(precision=6, scale=4), nullable=False, comment='Fractional mortality rate for this period (0.0 … 1.0).'),
    sa.CheckConstraint('average_weight_g >= 0', name='ck_prod_metric_avg_weight_non_negative'),
    sa.CheckConstraint('biomass_kg >= 0', name='ck_prod_metric_biomass_non_negative'),
    sa.CheckConstraint('fcr >= 0', name='ck_prod_metric_fcr_non_negative'),
    sa.CheckConstraint('feed_consumption_kg >= 0', name='ck_prod_metric_feed_non_negative'),
    sa.CheckConstraint('mortality_rate BETWEEN 0 AND 1', name='ck_prod_metric_mortality_range'),
    sa.CheckConstraint('population >= 0', name='ck_prod_metric_population_non_negative'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    comment='TimescaleDB hypertable — biological production snapshots per tank. Partition: recorded_at / 30-day chunks.'
    )
    op.create_index('ix_production_metrics_tank_recorded', 'tank_production_metrics', ['tank_id', 'recorded_at'], unique=False)
    op.create_table('vaccination_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('vaccine_name', sa.String(length=150), nullable=False, comment='Commercial or generic vaccine name.'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='Manufacturer batch/lot number for traceability.'),
    sa.Column('administered_by', sa.Uuid(), nullable=False, comment='FK → users.id  (veterinarian or certified operator).'),
    sa.Column('administered_at', sa.Date(), nullable=False, comment='Date the vaccine was administered.'),
    sa.Column('route', sa.String(length=50), nullable=False, comment="Administration route: 'Intraperitoneal' | 'Immersion' | 'Oral'."),
    sa.Column('dose_per_fish_ml', sa.Numeric(precision=6, scale=4), nullable=True, comment='Dose per individual fish in millilitres (where applicable).'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("route IN ('Intraperitoneal','Immersion','Oral')", name='ck_vaccination_route_valid'),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Vaccination events per tank — biosecurity compliance tracking.'
    )
    op.create_index('ix_vaccination_records_tank', 'vaccination_records', ['tank_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — referenced by Recommendation.insight_id.'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Insight generation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id — the tank this insight pertains to.'),
    sa.Column('source_model_id', sa.Uuid(), nullable=True, comment='FK → model_versions.id — the specific model version that generated this insight. Enables MLOps auditability and model performance tracking.'),
    sa.Column('historical_case_id', sa.Uuid(), nullable=True, comment='FK → historical_cases.id — if this insight was derived from a CBR case match, links back to the source historical case.'),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Short, actionable insight headline shown in the UI.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full narrative explanation of the insight and its supporting evidence.'),
    sa.Column('priority', sa.String(length=50), nullable=False, comment="'Info' | 'Medium' | 'High' | 'Critical'"),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence in this insight [0.0000 … 1.0000].'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiry timestamp. Insight is suppressed in the UI after this time. NULL = permanently active.'),
    sa.CheckConstraint("priority IN ('Info','Medium','High','Critical')", name='ck_ai_insight_priority_valid'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_ai_insight_confidence_range'),
    sa.ForeignKeyConstraint(['historical_case_id'], ['historical_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_model_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'generated_at'),
    comment='TimescaleDB hypertable — AI-synthesised insights for dashboards and the recommendation engine. Partition: generated_at / 30-day chunks.'
    )
    op.create_index('ix_ai_insights_active', 'ai_insights', ['tank_id', 'generated_at'], unique=False, postgresql_where='expires_at IS NULL OR expires_at > NOW()')
    op.create_index(op.f('ix_ai_insights_historical_case_id'), 'ai_insights', ['historical_case_id'], unique=False)
    op.create_index('ix_ai_insights_priority_active', 'ai_insights', ['priority', 'generated_at'], unique=False)
    op.create_index('ix_ai_insights_tank_generated', 'ai_insights', ['tank_id', 'generated_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable reference for notifications and audit.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Alert creation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('sensor_id', sa.Uuid(), nullable=True, comment='FK → sensors.id  (nullable: alert may originate from AI, not a sensor).'),
    sa.Column('type', sa.String(length=100), nullable=False, comment="Alert category (e.g. 'DO_DEPLETION', 'HIGH_AMMONIA', 'PSI_CRITICAL')."),
    sa.Column('severity', sa.String(length=50), nullable=False, comment="'Info' | 'Warning' | 'Critical'"),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Active' | 'Acknowledged' | 'Resolved'"),
    sa.Column('message', sa.Text(), nullable=False, comment='Human-readable alert description rendered in the UI.'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when an operator acknowledged the alert.'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the alert was resolved / cleared.'),
    sa.Column('resolved_by', sa.Uuid(), nullable=True, comment='FK → users.id  (operator who resolved the alert).'),
    sa.CheckConstraint("severity IN ('Info','Warning','Critical')", name='ck_alert_severity_valid'),
    sa.CheckConstraint("status IN ('Active','Acknowledged','Resolved')", name='ck_alert_status_valid'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — AI and threshold-breach alerts. Partition: time / 7-day chunks.'
    )
    op.create_index('ix_alerts_severity_status', 'alerts', ['severity', 'status'], unique=False)
    op.create_index('ix_alerts_tank_time', 'alerts', ['tank_id', 'time'], unique=False)
    op.create_table('biosecurity_records',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable reference for quarantine and compliance records.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Detection timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('pathogen_id', sa.Uuid(), nullable=False, comment='FK → pathogens.id  (RESTRICT: retain detection records even if pathogen is updated).'),
    sa.Column('inspection_id', sa.Uuid(), nullable=True, comment='FK → inspections.id — the manual inspection that triggered this record (if any).'),
    sa.Column('detection_method', sa.String(length=100), nullable=False, comment="'qPCR Test' | 'Visual Count' | 'Microscopy' | 'eDNA Analysis'."),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False, comment='Quantified detection value (e.g. lice count per fish, Ct value, copies/µL).'),
    sa.Column('inspection_date', sa.Date(), nullable=False, comment='Calendar date of the physical inspection or sample collection.'),
    sa.Column('risk_level', sa.String(length=50), nullable=False, comment="'Safe' | 'Warning' | 'Critical'."),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Active' | 'Under Treatment' | 'Resolved' | 'Monitoring'."),
    sa.Column('treatment', sa.String(length=200), nullable=True, comment="Prescribed or applied treatment protocol (e.g. 'Hydrogen Peroxide Bath', 'Emamectin Benzoate Feed Treatment')."),
    sa.CheckConstraint("detection_method IN ('qPCR Test','Visual Count','Microscopy','eDNA Analysis')", name='ck_biosecurity_detection_method_valid'),
    sa.CheckConstraint("risk_level IN ('Safe','Warning','Critical')", name='ck_biosecurity_risk_level_valid'),
    sa.CheckConstraint("status IN ('Active','Under Treatment','Resolved','Monitoring')", name='ck_biosecurity_status_valid'),
    sa.CheckConstraint('value >= 0', name='ck_biosecurity_value_non_negative'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pathogen_id'], ['pathogens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — pathogen detection and biosecurity events per tank. Partition: time / 14-day chunks.'
    )
    op.create_index('ix_biosecurity_records_pathogen', 'biosecurity_records', ['pathogen_id', 'time'], unique=False)
    op.create_index('ix_biosecurity_records_risk_status', 'biosecurity_records', ['risk_level', 'status'], unique=False)
    op.create_index('ix_biosecurity_records_tank_time', 'biosecurity_records', ['tank_id', 'time'], unique=False)
    op.create_table('calibrations',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable reference for foreign keys.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Calibration timestamp (TimescaleDB partition key).'),
    sa.Column('sensor_id', sa.Uuid(), nullable=False, comment='FK → sensors.id'),
    sa.Column('operator_id', sa.Uuid(), nullable=False, comment='FK → users.id  (RESTRICT preserves calibration audit trail).'),
    sa.Column('offset_value', sa.Numeric(precision=10, scale=4), nullable=False, comment='Calibration offset applied to raw sensor readings.'),
    sa.Column('variance', sa.Numeric(precision=10, scale=4), nullable=False, comment='Measured variance from reference standard.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'success' or 'failed'."),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('success','failed')", name='ck_calibration_status_valid'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — sensor calibration history. Partition: time / 30-day chunks.'
    )
    op.create_index('ix_calibrations_sensor_time', 'calibrations', ['sensor_id', 'time'], unique=False)
    op.create_table('data_quality_checks',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Validation execution timestamp (TimescaleDB partition key).'),
    sa.Column('sensor_id', sa.Uuid(), nullable=False, comment="FK → sensors.id — which sensor's data was validated."),
    sa.Column('validation_type', sa.String(length=100), nullable=False, comment="'Range Check' | 'Stuck Sensor Check' | 'Drift Scan' | 'Spike Filter'."),
    sa.Column('result', sa.String(length=50), nullable=False, comment="'Pass' | 'Fail' | 'Suspect'."),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Anomaly severity score [0.0 = normal … 1.0 = extreme anomaly]. Computed by the validation algorithm (e.g. z-score normalised to 0-1).'),
    sa.CheckConstraint("result IN ('Pass','Fail','Suspect')", name='ck_dqc_result_valid'),
    sa.CheckConstraint("validation_type IN ('Range Check','Stuck Sensor Check','Drift Scan','Spike Filter')", name='ck_dqc_validation_type_valid'),
    sa.CheckConstraint('anomaly_score BETWEEN 0 AND 1', name='ck_dqc_anomaly_score_range'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — automated sensor data quality checks. Partition: time / 7-day chunks. Powers the Data Quality Dashboard and ML feature store gating.'
    )
    op.create_index('ix_data_quality_checks_result', 'data_quality_checks', ['result', 'time'], unique=False)
    op.create_index('ix_data_quality_checks_sensor_time', 'data_quality_checks', ['sensor_id', 'time'], unique=False)
    op.create_table('disease_predictions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier for case-match references.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Prediction generation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('model_version_id', sa.Uuid(), nullable=True, comment='FK → model_versions.id — model that generated this forecast.'),
    sa.Column('disease_name', sa.String(length=150), nullable=False, comment="Pathogen or syndrome name (e.g. 'Amoebic Gill Disease', 'Infectious Haematopoietic Necrosis', 'Sea Lice Infestation')."),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=2), nullable=False, comment='Disease outbreak risk score [0.00 = negligible … 10.00 = critical].'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence in this disease prediction [0.0000 … 1.0000].'),
    sa.Column('forecast_days', sa.Integer(), nullable=False, comment='Prediction horizon in days (e.g. 7, 14, 30).'),
    sa.Column('confidence_low', sa.Numeric(precision=5, scale=4), nullable=True, comment='Lower bound of the 90% confidence interval for risk_score.'),
    sa.Column('confidence_high', sa.Numeric(precision=5, scale=4), nullable=True, comment='Upper bound of the 90% confidence interval for risk_score.'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_disease_confidence_range'),
    sa.CheckConstraint('forecast_days > 0', name='ck_disease_forecast_days_positive'),
    sa.CheckConstraint('risk_score BETWEEN 0.00 AND 10.00', name='ck_disease_risk_score_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — disease risk predictions per tank. Partition: time / 14-day chunks.'
    )
    op.create_index('ix_disease_predictions_disease', 'disease_predictions', ['disease_name', 'time'], unique=False)
    op.create_index('ix_disease_predictions_tank_time', 'disease_predictions', ['tank_id', 'time'], unique=False)
    op.create_table('harvest_predictions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Prediction generation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('model_version_id', sa.Uuid(), nullable=True, comment='FK → model_versions.id — model that generated this forecast.'),
    sa.Column('predicted_harvest_date', sa.Date(), nullable=False, comment='Projected optimal harvest date (calendar date, not timestamp).'),
    sa.Column('projected_biomass', sa.Numeric(precision=12, scale=2), nullable=False, comment='Expected total live weight (kg) at the projected harvest date.'),
    sa.Column('projected_mean_weight_g', sa.Numeric(precision=10, scale=2), nullable=False, comment='Projected mean individual fish weight (g) at harvest.'),
    sa.Column('growth_rate_fcr', sa.Numeric(precision=4, scale=2), nullable=False, comment='Feed Conversion Ratio trajectory used in the growth forecast model.'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence in the harvest forecast [0.0000 … 1.0000].'),
    sa.Column('revenue_projection_usd', sa.Numeric(precision=15, scale=2), nullable=True, comment='Estimated gross revenue (USD) at projected biomass and current market price. Populated when market price data is available.'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_harvest_confidence_range'),
    sa.CheckConstraint('growth_rate_fcr > 0', name='ck_harvest_fcr_positive'),
    sa.CheckConstraint('projected_biomass > 0', name='ck_harvest_biomass_positive'),
    sa.CheckConstraint('projected_mean_weight_g > 0', name='ck_harvest_mean_weight_positive'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — harvest readiness predictions per tank. Partition: time / 30-day chunks.'
    )
    op.create_index('ix_harvest_predictions_tank_time', 'harvest_predictions', ['tank_id', 'time'], unique=False)
    op.create_table('model_health_metrics',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='Evaluation timestamp (TimescaleDB partition key).'),
    sa.Column('model_version_id', sa.Uuid(), nullable=False, comment='FK → model_versions.id — which version these metrics were evaluated against.'),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True, comment='Classification accuracy [0.0 … 1.0].'),
    sa.Column('precision', sa.Numeric(precision=5, scale=4), nullable=True, comment='Precision (positive predictive value) [0.0 … 1.0].'),
    sa.Column('recall', sa.Numeric(precision=5, scale=4), nullable=True, comment='Recall (sensitivity / true positive rate) [0.0 … 1.0].'),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Harmonic mean of precision and recall [0.0 … 1.0].'),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Fraction of model inputs that passed data quality checks in this evaluation window [0.0 … 1.0]. Low scores indicate upstream sensor/pipeline issues.'),
    sa.Column('agreement_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Inter-model agreement coefficient for ensemble models [0.0 … 1.0]. Measures consistency between sub-model predictions.'),
    sa.CheckConstraint('accuracy        IS NULL OR accuracy        BETWEEN 0 AND 1', name='ck_mhm_accuracy_range'),
    sa.CheckConstraint('agreement_score IS NULL OR agreement_score BETWEEN 0 AND 1', name='ck_mhm_agreement_range'),
    sa.CheckConstraint('data_quality_score IS NULL OR data_quality_score BETWEEN 0 AND 1', name='ck_mhm_dq_range'),
    sa.CheckConstraint('f1_score        IS NULL OR f1_score        BETWEEN 0 AND 1', name='ck_mhm_f1_range'),
    sa.CheckConstraint('precision       IS NULL OR precision       BETWEEN 0 AND 1', name='ck_mhm_precision_range'),
    sa.CheckConstraint('recall          IS NULL OR recall          BETWEEN 0 AND 1', name='ck_mhm_recall_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    comment='TimescaleDB hypertable — MLOps performance snapshots per model version. Partition: recorded_at / 90-day chunks. Powers the Settings page AI Operations Monitor.'
    )
    op.create_index('ix_model_health_metrics_version_time', 'model_health_metrics', ['model_version_id', 'recorded_at'], unique=False)
    op.create_table('mortality_predictions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable row identifier.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Prediction generation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('model_version_id', sa.Uuid(), nullable=True, comment='FK → model_versions.id — model that generated this forecast.'),
    sa.Column('mortality_probability', sa.Numeric(precision=6, scale=4), nullable=False, comment='Predicted probability of elevated mortality in the forecast window [0.0 … 1.0].'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence in this forecast [0.0000 … 1.0000].'),
    sa.Column('forecast_days', sa.Integer(), nullable=False, comment='Forecast horizon in days: 7 | 14 | 30.'),
    sa.Column('confidence_low', sa.Numeric(precision=6, scale=4), nullable=True, comment='Lower bound of the 90% CI for mortality_probability.'),
    sa.Column('confidence_high', sa.Numeric(precision=6, scale=4), nullable=True, comment='Upper bound of the 90% CI for mortality_probability.'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_mortality_confidence_range'),
    sa.CheckConstraint('forecast_days IN (7, 14, 30)', name='ck_mortality_forecast_days_valid'),
    sa.CheckConstraint('mortality_probability BETWEEN 0 AND 1', name='ck_mortality_probability_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — mortality risk probability forecasts per tank. Partition: time / 14-day chunks.'
    )
    op.create_index('ix_mortality_predictions_tank_time', 'mortality_predictions', ['tank_id', 'time'], unique=False)
    op.create_table('psi_predictions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — referenced by psi_factors composite FK.'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='Inference timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('model_version_id', sa.Uuid(), nullable=True, comment='FK → model_versions.id — which model version produced this prediction.'),
    sa.Column('psi_score', sa.Numeric(precision=4, scale=2), nullable=False, comment='Composite stress index [0.00 = optimal … 10.00 = critical stress].'),
    sa.Column('stress_level', sa.String(length=50), nullable=False, comment="Human-readable stress classification derived from psi_score. 'Optimal' | 'Mild Stress' | 'Moderate Stress' | 'Severe Stress' | 'Critical Stress'."),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence in this prediction [0.0000 … 1.0000].'),
    sa.CheckConstraint("stress_level IN ('Optimal','Mild Stress','Moderate Stress','Severe Stress','Critical Stress')", name='ck_psi_stress_level_valid'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_psi_confidence_range'),
    sa.CheckConstraint('psi_score BETWEEN 0.00 AND 10.00', name='ck_psi_score_range'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'generated_at'),
    comment='TimescaleDB hypertable — PSI AI inference outputs. Partition: generated_at / 7-day chunks.'
    )
    op.create_index('ix_psi_predictions_tank_generated', 'psi_predictions', ['tank_id', 'generated_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — referenced by recommendation_feedback.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Recommendation generation timestamp (TimescaleDB partition key).'),
    sa.Column('tank_id', sa.Uuid(), nullable=False, comment='FK → tanks.id'),
    sa.Column('generated_by_model', sa.Uuid(), nullable=True, comment='FK → model_versions.id — the model version that generated this recommendation. Enables MLOps traceability.'),
    sa.Column('action', sa.String(length=200), nullable=False, comment="Short imperative action title shown in the UI (e.g. 'Increase aeration')."),
    sa.Column('expected_outcome', sa.Text(), nullable=False, comment='Narrative description of what the action will achieve.'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='Model confidence score for this recommendation [0.0 … 1.0].'),
    sa.Column('priority', sa.String(length=50), nullable=False, comment="'Low' | 'Medium' | 'High' | 'Critical'"),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'Pending' | 'Accepted' | 'Dismissed' | 'Completed'"),
    sa.Column('resolved_by', sa.Uuid(), nullable=True, comment='FK → users.id  (operator who acted on the recommendation).'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the recommendation was actioned or dismissed.'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Free-text operator notes on the resolution.'),
    sa.CheckConstraint("priority IN ('Low','Medium','High','Critical')", name='ck_recommendation_priority_valid'),
    sa.CheckConstraint("status IN ('Pending','Accepted','Dismissed','Completed')", name='ck_recommendation_status_valid'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_recommendation_confidence_range'),
    sa.ForeignKeyConstraint(['generated_by_model'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — AI-generated operational recommendations. Partition: time / 30-day chunks.'
    )
    op.create_index('ix_recommendations_status_priority', 'recommendations', ['status', 'priority'], unique=False)
    op.create_index('ix_recommendations_tank_time', 'recommendations', ['tank_id', 'time'], unique=False)
    op.create_table('sensor_health',
    sa.Column('sensor_id', sa.Uuid(), nullable=False, comment='FK → sensors.id  (also the sole PK — 1-to-1 relationship).'),
    sa.Column('signal_strength', sa.String(length=50), nullable=False, comment="RF/LoRa/Ethernet signal quality: 'Strong' | 'Medium' | 'Weak' | 'Offline'."),
    sa.Column('battery_level', sa.Numeric(precision=5, scale=2), nullable=True, comment='Battery percentage (0–100). NULL for wired/PoE sensors.'),
    sa.Column('drift_score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Sensor drift index [0.0 = no drift). Triggers maintenance alert when > 0.05.'),
    sa.Column('health_status', sa.String(length=50), nullable=False, comment="Overall diagnosis: 'Optimal' | 'Warning' | 'Maintenance Required' | 'Fault'."),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the most recent heartbeat / telemetry packet.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Row-level update timestamp (auto-maintained).'),
    sa.CheckConstraint("health_status IN ('Optimal','Warning','Maintenance Required','Fault')", name='ck_sensor_health_status_valid'),
    sa.CheckConstraint("signal_strength IN ('Strong','Medium','Weak','Offline')", name='ck_sensor_health_signal_valid'),
    sa.CheckConstraint('battery_level BETWEEN 0 AND 100', name='ck_sensor_health_battery_range'),
    sa.CheckConstraint('drift_score >= 0', name='ck_sensor_health_drift_non_negative'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sensor_id'),
    comment='Live sensor health snapshot — 1-to-1 with sensors table.'
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID — stable FK target for downstream references.'),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='Reading timestamp (TimescaleDB partition key).'),
    sa.Column('sensor_id', sa.Uuid(), nullable=False, comment='FK → sensors.id  (RESTRICT: retain readings even if sensor is decommissioned).'),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False, comment="Numeric sensor reading in the sensor's native unit."),
    sa.Column('raw_payload', sa.JSON(), nullable=True, comment='Full MQTT JSON payload for audit / re-processing.'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'time'),
    comment='TimescaleDB hypertable — raw IoT sensor readings. Partition: time / 1-day chunks.'
    )
    op.create_index('ix_telemetry_sensor_time', 'telemetry', ['sensor_id', 'time'], unique=False)
    op.create_table('psi_factors',
    sa.Column('prediction_id', sa.Uuid(), nullable=False, comment='FK → psi_predictions.id  (part of composite PK and composite FK).'),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False, comment='FK → psi_predictions.generated_at  (TimescaleDB partition key).'),
    sa.Column('factor_name', sa.String(length=100), nullable=False, comment="Name of the environmental/biological factor. One of: 'temperature' | 'dissolved_oxygen' | 'pH' | 'ammonia' | 'salinity' | 'stocking_density'."),
    sa.Column('contribution', sa.Numeric(precision=6, scale=4), nullable=False, comment='Signed SHAP-style contribution to the PSI score. Positive = increases stress; negative = reduces stress.'),
    sa.Column('importance_score', sa.Numeric(precision=6, scale=4), nullable=False, comment='Absolute feature importance weight [≥ 0.0000].'),
    sa.CheckConstraint("factor_name IN ('temperature','dissolved_oxygen','pH','ammonia','salinity','stocking_density')", name='ck_psi_factor_name_valid'),
    sa.CheckConstraint('importance_score >= 0', name='ck_psi_factor_importance_non_negative'),
    sa.ForeignKeyConstraint(['prediction_id', 'prediction_time'], ['psi_predictions.id', 'psi_predictions.generated_at'], name='fk_psi_factors_prediction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id', 'prediction_time', 'factor_name'),
    comment='TimescaleDB hypertable — XAI factor breakdown per PSI prediction. Partition: prediction_time / 7-day chunks.'
    )
    op.create_index('ix_psi_factors_prediction', 'psi_factors', ['prediction_id', 'prediction_time'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Surrogate UUID identifier for the UI action.'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False, comment='Action execution timestamp (TimescaleDB partition key).'),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False, comment='FK → recommendations.id (part of composite FK).'),
    sa.Column('recommendation_time', sa.DateTime(timezone=True), nullable=False, comment='FK → recommendations.time (part of composite FK).'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id (operator who took the action).'),
    sa.Column('action', sa.String(), nullable=False, comment="Action taken: 'Accepted' | 'Rejected' | 'Ignored'"),
    sa.CheckConstraint("action IN ('Accepted', 'Rejected', 'Ignored')", name='ck_rec_action_valid'),
    sa.ForeignKeyConstraint(['recommendation_id', 'recommendation_time'], ['recommendations.id', 'recommendations.time'], name='fk_rec_actions_recommendation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'executed_at'),
    comment='TimescaleDB hypertable — operator UI actions (accept/reject/ignore) on recommendations. Partition: executed_at / 30-day chunks.'
    )
    op.create_index('ix_rec_actions_rec_composite', 'recommendation_actions', ['recommendation_id', 'recommendation_time'], unique=False)
    op.create_index(op.f('ix_recommendation_actions_user_id'), 'recommendation_actions', ['user_id'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False, comment='FK → recommendations.id  (part of composite PK).'),
    sa.Column('recommendation_time', sa.DateTime(timezone=True), nullable=False, comment='FK → recommendations.time  (TimescaleDB partition key).'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='FK → users.id  (RESTRICT preserves feedback authorship).'),
    sa.Column('action_taken', sa.String(length=100), nullable=False, comment="What the operator did: 'Applied Remediation' | 'Alternative Action Taken' | 'Ignored - False Alarm' | 'Ignored - Operational Constraints'."),
    sa.Column('effectiveness_score', sa.Integer(), nullable=False, comment='Operator rating of recommendation effectiveness: 1 (poor) … 5 (excellent).'),
    sa.Column('comments', sa.Text(), nullable=True, comment='Optional free-text operator commentary on the recommendation outcome.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Feedback submission timestamp.'),
    sa.CheckConstraint("action_taken IN ('Applied Remediation','Alternative Action Taken','Ignored - False Alarm','Ignored - Operational Constraints')", name='ck_rec_feedback_action_valid'),
    sa.CheckConstraint('effectiveness_score BETWEEN 1 AND 5', name='ck_rec_feedback_effectiveness_range'),
    sa.ForeignKeyConstraint(['recommendation_id', 'recommendation_time'], ['recommendations.id', 'recommendations.time'], name='fk_rec_feedback_recommendation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('recommendation_id', 'recommendation_time'),
    comment='TimescaleDB hypertable — operator feedback on AI recommendations. Partition: recommendation_time / 30-day chunks.'
    )
    op.create_index('ix_rec_feedback_recommendation', 'recommendation_feedback', ['recommendation_id', 'recommendation_time'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)

    # Convert designated tables to TimescaleDB hypertables (PostgreSQL only)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("SELECT create_hypertable('telemetry', 'time', chunk_time_interval => INTERVAL '1 day')")
        op.execute("SELECT create_hypertable('calibrations', 'time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('audit_logs', 'time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('tank_environment_snapshots', 'captured_at', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('tank_production_metrics', 'recorded_at', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('alerts', 'time', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('recommendations', 'time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('recommendation_feedback', 'recommendation_time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('recommendation_actions', 'executed_at', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('notifications', 'time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('psi_predictions', 'generated_at', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('psi_factors', 'prediction_time', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('disease_predictions', 'time', chunk_time_interval => INTERVAL '14 days')")
        op.execute("SELECT create_hypertable('mortality_predictions', 'time', chunk_time_interval => INTERVAL '14 days')")
        op.execute("SELECT create_hypertable('harvest_predictions', 'time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('case_matches', 'matched_at', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('ai_insights', 'generated_at', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('biosecurity_records', 'time', chunk_time_interval => INTERVAL '14 days')")
        op.execute("SELECT create_hypertable('model_health_metrics', 'recorded_at', chunk_time_interval => INTERVAL '90 days')")
        op.execute("SELECT create_hypertable('ml_feature_store', 'feature_timestamp', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('data_quality_checks', 'time', chunk_time_interval => INTERVAL '7 days')")
        op.execute("SELECT create_hypertable('digital_twin_snapshots', 'simulation_time', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('farm_health_snapshots', 'recorded_at', chunk_time_interval => INTERVAL '30 days')")
        op.execute("SELECT create_hypertable('system_health_snapshots', 'recorded_at', chunk_time_interval => INTERVAL '30 days')")

    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index('ix_rec_feedback_recommendation', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_actions_user_id'), table_name='recommendation_actions')
    op.drop_index('ix_rec_actions_rec_composite', table_name='recommendation_actions')
    op.drop_table('recommendation_actions')
    op.drop_index('ix_psi_factors_prediction', table_name='psi_factors')
    op.drop_table('psi_factors')
    op.drop_index('ix_telemetry_sensor_time', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('sensor_health')
    op.drop_index('ix_recommendations_tank_time', table_name='recommendations')
    op.drop_index('ix_recommendations_status_priority', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_psi_predictions_tank_generated', table_name='psi_predictions')
    op.drop_table('psi_predictions')
    op.drop_index('ix_mortality_predictions_tank_time', table_name='mortality_predictions')
    op.drop_table('mortality_predictions')
    op.drop_index('ix_model_health_metrics_version_time', table_name='model_health_metrics')
    op.drop_table('model_health_metrics')
    op.drop_index('ix_harvest_predictions_tank_time', table_name='harvest_predictions')
    op.drop_table('harvest_predictions')
    op.drop_index('ix_disease_predictions_tank_time', table_name='disease_predictions')
    op.drop_index('ix_disease_predictions_disease', table_name='disease_predictions')
    op.drop_table('disease_predictions')
    op.drop_index('ix_data_quality_checks_sensor_time', table_name='data_quality_checks')
    op.drop_index('ix_data_quality_checks_result', table_name='data_quality_checks')
    op.drop_table('data_quality_checks')
    op.drop_index('ix_calibrations_sensor_time', table_name='calibrations')
    op.drop_table('calibrations')
    op.drop_index('ix_biosecurity_records_tank_time', table_name='biosecurity_records')
    op.drop_index('ix_biosecurity_records_risk_status', table_name='biosecurity_records')
    op.drop_index('ix_biosecurity_records_pathogen', table_name='biosecurity_records')
    op.drop_table('biosecurity_records')
    op.drop_index('ix_alerts_tank_time', table_name='alerts')
    op.drop_index('ix_alerts_severity_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_ai_insights_tank_generated', table_name='ai_insights')
    op.drop_index('ix_ai_insights_priority_active', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_historical_case_id'), table_name='ai_insights')
    op.drop_index('ix_ai_insights_active', table_name='ai_insights', postgresql_where='expires_at IS NULL OR expires_at > NOW()')
    op.drop_table('ai_insights')
    op.drop_index('ix_vaccination_records_tank', table_name='vaccination_records')
    op.drop_table('vaccination_records')
    op.drop_index('ix_production_metrics_tank_recorded', table_name='tank_production_metrics')
    op.drop_table('tank_production_metrics')
    op.drop_index('ix_env_snapshot_tank_captured', table_name='tank_environment_snapshots')
    op.drop_table('tank_environment_snapshots')
    op.drop_index(op.f('ix_sensors_tank_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_hardware_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_quarantine_events_tank_id'), table_name='quarantine_events')
    op.drop_table('quarantine_events')
    op.drop_index('ix_model_versions_model_status', table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_index('ix_model_versions_is_active', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_ml_feature_store_tank_ts', table_name='ml_feature_store')
    op.drop_index('ix_ml_feature_store_source', table_name='ml_feature_store')
    op.drop_index('ix_ml_feature_store_group_ts', table_name='ml_feature_store')
    op.drop_table('ml_feature_store')
    op.drop_index(op.f('ix_inspections_tank_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_digital_twin_tank_sim_time', table_name='digital_twin_snapshots')
    op.drop_index('ix_digital_twin_scenario', table_name='digital_twin_snapshots')
    op.drop_table('digital_twin_snapshots')
    op.drop_index('ix_compliance_records_type_status', table_name='compliance_records')
    op.drop_index('ix_compliance_records_farm', table_name='compliance_records')
    op.drop_table('compliance_records')
    op.drop_table('user_farm_mappings')
    op.drop_index(op.f('ix_threshold_configs_updated_by'), table_name='threshold_configs')
    op.drop_index('ix_threshold_configs_metric', table_name='threshold_configs')
    op.drop_index('ix_threshold_configs_farm', table_name='threshold_configs')
    op.drop_table('threshold_configs')
    op.drop_index(op.f('ix_tanks_zone_id'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_index('ix_notifications_user_time', table_name='notifications')
    op.drop_index('ix_notifications_read_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_models_status', table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_owner_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_index('ix_ai_models_algorithm', table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_zones_farm_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_farm_health_snapshots_farm_recorded', table_name='farm_health_snapshots')
    op.drop_table('farm_health_snapshots')
    op.drop_index('ix_case_matches_similarity', table_name='case_matches')
    op.drop_index('ix_case_matches_prediction', table_name='case_matches')
    op.drop_index('ix_case_matches_case_id', table_name='case_matches')
    op.drop_table('case_matches')
    op.drop_index('ix_system_health_snapshots_recorded', table_name='system_health_snapshots')
    op.drop_table('system_health_snapshots')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('pathogens')
    op.drop_index('ix_historical_cases_severity', table_name='historical_cases')
    op.drop_index('ix_historical_cases_scenario_type', table_name='historical_cases')
    op.drop_table('historical_cases')
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
